### ISSUE TITLE
LanguageTool Premium Account Credentials

### ISSUE THREAD

**Issue by k0nze** [vigoux/ltex-ls.nvim#2]
I setup `ltex-ls.nvim` using `mason` and `lspconfig` and I was wondering if it is possible to connect to a premium LanguageTool premium account?

**Comment by PlexSheep** [comment]
It is possible to do. I am using my premium account with ltex.
you need to configure ltex like so:
```lua
  M.ltex.languageToolOrg = {
    apiKey = "somepassword",
    username = "me@example.com",
    languageToolHttpServerUrl = "https://api.languagetoolplus.com/v2/",
  }
  M.ltex.languageToolHttpServerUrl = "https://api.languagetoolplus.com/v2/"
```
it's a bit hacky and can probably be made simpler, but I it was just something I hacked together.

**WARNING**: If you have your neovim configs in a public version control like me, be careful not to expose your apikey to the public. you may want to redact your username too.

**Comment by k0nze** [comment]
Perfect! Thank you.

**Comment by jonnykl** [comment]
> ```lua
>   M.ltex.languageToolOrg = {
>     apiKey = "somepassword",
>     username = "me@example.com",
>     languageToolHttpServerUrl = "https://api.languagetoolplus.com/v2/",
>   }
>   M.ltex.languageToolHttpServerUrl = "https://api.languagetoolplus.com/v2/"
> ```

I'm also using `ltex-ls.nvim` with `mason` and `lspconfig`. But I don't understand where to put these lines?
