### ISSUE TITLE
Macros not spellchecked

### ISSUE THREAD

**Issue by mm-crj** [vigoux/ltex-ls.nvim#3]
This is more of a feature request than an issue. So I use ltex-ls to run grammar checks on my thesis and papers as I write them. However, it ignores the latex macros completely. Let me illustrate this with an example. I have a macro  

`\newcommand{\ie}{\emph{i.e.,}}` 

and if I accidentally put `\ie,` somewhere in the tex document, it will not flag it for two consecutive commas. Let's see another example, I use 

`\newcommand{\boss}[1]{{\color{red}{\textbf{Boss:}\textit{ #1} }}}
\newcommand{\me}[1]{{\color{violet}{\textbf{Me:}\textit{ #1}}}}
`

to write down comments in the documents (much simpler than using packages, believe me I tried). However, ltex will not treat this as new lines as this is a macro. I think it's also the case that sentence detection is poor when a sentence is continued with an equation or align environment. Thank you!

**Comment by vigoux** [comment]
Hi ! 

This issue has to be reported on ltex's github page directly rather than on here.

We only handle the integration within neovim of the LSP server, and not LSP server features.
